export const GRAPHHOPPER_API_KEY = process.env.REACT_APP_GRAPHHOPPER_API_KEY;
export const OPENWEATHER_API_KEY = process.env.REACT_APP_OPENWEATHER_API_KEY;
export const OPENTRIPMAP_API_KEY = process.env.REACT_APP_OPENTRIPMAP_API_KEY;
